### ISSUE TITLE
comunication between cordova and unity

### ISSUE THREAD

**Issue by pauloagsantos** [alantom1423/cordova-plugin-unityar#2]
Hi. i can exit from unity app and return to cordova and see the message that i have send. but i can't discover how receive the message send from cordova to unity:

UnityAR.launchWithMessage("Manager","GetMessageFromCordova","Cordova Msg", 
     (data)=>{ 
     console.log("success ",data); 
     },(err)=>{ 
     console.log("error ",err); 
     }); 

whats is Manager? is a GameObject?
where is GetMessageFromCordova?

**Comment by alantom1423** [comment]
Hi @pauloagsantos 
    As specified in the example
`UnityAR.launchWithMessage("Manager","GetMessageFromCordova","Cordova Msg",`

Create a Gameobject called _Manager_ in your scene
Create a script and attach it to _Manager_
Write a public method _GetMessageFromCordova_ in the script with a _string argument_.

`public void GetMessageFromCordova(string message)`.  Debug the message or Print it on a textfield in your scene

You can send message to any gameobject with a public method attached to it with an argument
`UnityAR.launchWithMessage(GameObject,MethodName,Argument)
`
